<?php
/**
 * Copyright © Q-Solutions Studio: eCommerce Nanobots. All rights reserved.
 * @author      Jakub Winkler <jwinkler@qsolutionsstudio.com>
 *
 * @category    Nanobots
 * @package     Nanobots_AttributeOptionPager
 */

use Nanobots\AttributeOptionPager\Block\Adminhtml\Attribute\Edit\Options\Options;

/** @var $block Options */
$stores = $block->getStoresSortedBySortOrder();
?>
<fieldset class="admin__fieldset fieldset">
    <legend class="legend">
        <span><?= $block->escapeHtml(__('Manage Options (Values of Your Attribute)' )) ?></span>
    </legend><br />
    <div class="admin__control-table-wrapper" id="manage-options-panel" data-index="attribute_options_select_container">
        <div class="admin__data-grid-pager-wrap attribute-pager">
            <label for="attributeGrid_page-limit"></label><select name="limit" id="attributeGrid_page-limit" class="admin__control-select attribute-pager-limit">
                <?php foreach ($block->getLimits() as $limit): ?>
                    <option value="<?= $limit;?>" <?= $block->getCurrentPageSize() === $limit ? 'selected="selected"' : '';?> data-url="<?= $block->getNextUrl($limit , $block->getCurrentPageNumber()); ?>"><?= $limit; ?></option>
                <?php endforeach; ?>
            </select>
            <label for="attributeGridattributeGrid_page-limit" class="admin__control-support-text"><?= __('per page'); ?></label>

            <div class="admin__data-grid-pager">
                <button type="button" class="attribute-pager-btn action-previous <?= $block->getCurrentPageNumber() === 1 ? 'disabled' :
                    '" data-url="' . $block->getNextUrl($block->getCurrentPageSize() , $block->getCurrentPageNumber() - 1); ?>">
                    <span><?= __('Previous page'); ?></span>
                </button>
                <input type="number" id="attributeGrid_page-current" min="1" max="<?= $block->getMaxPageCount() ?>" name="page" value="<?= $block->getCurrentPageNumber(); ?>"
                       data-url="<?= $block->getNextUrl($block->getCurrentPageSize() , 0) ?>" class="admin__control-text attribute-pager-current" data-ui-id="adminhtml-product-attribute-grid-current-page">
                <label class="admin__control-support-text" for="attributeGrid_page-current">
                    <?= __('of');?> <span> <?= $block->getMaxPageCount(); ?> </span>                        </label>
                <button type="button" class="attribute-pager-btn action-next <?= $block->getMaxPageCount() === $block->getCurrentPageNumber() ? ' disabled"' :
                    '" data-url="' . $block->getNextUrl($block->getCurrentPageSize() , $block->getCurrentPageNumber() + 1); ?>">
                    <span><?= __('Next page'); ?></span>
                </button>
            </div>
        </div>
        <table class="admin__control-table" data-index="attribute_options_select">
            <thead>
            <tr id="attribute-options-table">
                <th class="col-default control-table-actions-th">
                    <span><?= $block->escapeHtml(__('Is Default')) ?></span>
                </th>
                <?php
                foreach ($stores as $_store) :?>
                    <th<?php if ($_store->getId() == \Magento\Store\Model\Store::DEFAULT_STORE_ID) :?> class="_required"<?php endif; ?>>
                        <span><?= $block->escapeHtml(__($_store->getName())) ?></span>
                    </th>
                <?php endforeach;
                $storeTotal = count($stores) + 3;
                ?>
                <th class="col-sort"><span><?= $block->escapeHtml(__('Sort Order')) ?></span></th>
                <th class="col-delete">&nbsp;</th>
            </tr>

            </thead>
            <tbody data-role="options-container" class="ignore-validate"></tbody>
            <tfoot>
            <tr>
                <th colspan="<?= (int)$storeTotal ?>" class="validation">
                    <input type="hidden" class="required-dropdown-attribute-entry" name="dropdown_attribute_validation"/>
                    <input type="hidden" class="required-dropdown-attribute-unique" name="dropdown_attribute_validation_unique"/>
                </th>
            </tr>
            <tr>
                <th colspan="<?= (int) $storeTotal ?>" class="col-actions-add">
                    <?php if (!$block->getReadOnly() && !$block->canManageOptionDefaultOnly()) :?>
                        <button id="add_new_option_button" data-action="add_new_row"
                                title="<?= $block->escapeHtmlAttr(__('Add Option')) ?>"
                                type="button" class="action- scalable add">
                            <span><?= $block->escapeHtml(__('Add Option')) ?></span>
                        </button>
                    <?php endif; ?>
                </th>
            </tr>
            </tfoot>
        </table>
        <input type="hidden" id="option-count-check" value="" />
    </div>
    <script id="row-template" type="text/x-magento-template">
        <tr <% if (data.rowClasses) { %>class="<%- data.rowClasses %>"<% } %>>
        <td class="col-default control-table-actions-cell">
            <input class="input-radio" type="<%- data.intype %>" name="default[]" value="<%- data.id %>" <%- data.checked %><?php if ($block->getReadOnly()) :?>disabled="disabled"<?php endif;?>/>
        </td>
        <?php foreach ($stores as $_store) :?>
            <td class="col-<%- data.id %>"><input name="option[value][<%- data.id %>][<?= (int) $_store->getId() ?>]" value="<%- data.store<?= /* @noEscape */ (int) $_store->getId() ?> %>" class="input-text<?php if ($_store->getId() == \Magento\Store\Model\Store::DEFAULT_STORE_ID) :?> required-option required-unique<?php endif; ?>" type="text" <?php if ($block->getReadOnly() || $block->canManageOptionDefaultOnly()) :?> disabled="disabled"<?php endif;?>/></td>
        <?php endforeach; ?>
        <td class="col-default">
            <?php if (!$block->getReadOnly() && !$block->canManageOptionDefaultOnly()) :?>
                <input data-role="order" type="text" name="option[order][<%- data.id %>]"  value="<%- data.sort_order %>" <?php if ($block->getReadOnly() || $block->canManageOptionDefaultOnly()) :?> disabled="disabled"<?php endif; ?>/>
            <?php endif; ?>
        </td>
        <td id="delete_button_container_<%- data.id %>" class="col-delete">
            <input type="hidden" class="delete-flag" name="option[delete][<%- data.id %>]" value="" />
            <?php if (!$block->getReadOnly() && !$block->canManageOptionDefaultOnly()) :?>
                <button id="delete_button_<%- data.id %>" title="<?= $block->escapeHtmlAttr(__('Delete')) ?>" type="button"
                        class="action- scalable delete delete-option"
                >
                    <span><?= $block->escapeHtml(__('Delete')) ?></span>
                </button>
            <?php endif;?>
        </td>
        </tr>
    </script>
    <?php
    $values = [];
    foreach ($block->getOptionValues() as $value) {
        $value = $value->getData();
        $values[] = is_array($value) ? array_map(function ($str) {
            return htmlspecialchars_decode($str, ENT_QUOTES);
        }, $value) : $value;
    }
    ?>
    <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Catalog/js/options": {
                    "attributesData": <?= /* @noEscape */ json_encode($values, JSON_HEX_QUOT) ?>,
                    "isSortable":  <?= (int)(!$block->getReadOnly() && !$block->canManageOptionDefaultOnly()) ?>,
                    "isReadOnly": <?= (int)$block->getReadOnly() ?>
                },
                "Magento_Catalog/catalog/product/attribute/unique-validate": {
                    "element": "required-dropdown-attribute-unique",
                    "message": "<?= $block->escapeHtml(__("The value of Admin must be unique.")) ?>"
                },
                "Nanobots_AttributeOptionPager/js/pager": {
                    "ajaxUrlValue": {}
                }
            }
        }
    </script>


</fieldset>
