<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 * Copyright © Q-Solutions Studio: eCommerce Nanobots. All rights reserved.
 * @author      Jakub Winkler <jwinkler@qsolutionsstudio.com>
 *
 * @category    Nanobots
 * @package     Nanobots_AttributeOptionPager
 */
// phpcs:disable PHPCompatibility.Miscellaneous.RemovedAlternativePHPTags.MaybeASPOpenTagFound
/** @var $block \Nanobots\AttributeOptionPager\Block\Adminhtml\Attribute\Edit\Options\Text */

$stores = $block->getStoresSortedBySortOrder();
?>
<fieldset class="fieldset">
    <legend class="legend">
        <span><?= $block->escapeHtml(__('Manage Swatch (Values of Your Attribute)')) ?></span>
    </legend>
    <div id="swatch-text-options-panel">
        <div class="admin__data-grid-pager-wrap attribute-pager">
            <label for="attributeGrid_page-limit"></label><select name="limit" id="attributeGrid_page-limit" class="admin__control-select attribute-pager-limit">
                <?php foreach ($block->getLimits() as $limit): ?>
                    <option value="<?= $limit;?>" <?= $block->getCurrentPageSize() === $limit ? 'selected="selected"' : '';?> data-url="<?= $block->getNextUrl($limit , $block->getCurrentPageNumber()); ?>"><?= $limit; ?></option>
                <?php endforeach; ?>
            </select>
            <label for="attributeGridattributeGrid_page-limit" class="admin__control-support-text"><?= __('per page'); ?></label>

            <div class="admin__data-grid-pager">
                <button type="button" class="attribute-pager-btn action-previous <?= $block->getCurrentPageNumber() === 1 ? 'disabled' :
                    '" data-url="' . $block->getNextUrl($block->getCurrentPageSize() , $block->getCurrentPageNumber() - 1); ?>">
                    <span><?= __('Previous page'); ?></span>
                </button>
                <input type="number" id="attributeGrid_page-current" min="1" max="<?= $block->getMaxPageCount() ?>" name="page" value="<?= $block->getCurrentPageNumber(); ?>"
                       data-url="<?= $block->getNextUrl($block->getCurrentPageSize() , 0) ?>" class="admin__control-text attribute-pager-current" data-ui-id="adminhtml-product-attribute-grid-current-page">
                <label class="admin__control-support-text" for="attributeGrid_page-current">
                    <?= __('of');?> <span> <?= $block->getMaxPageCount(); ?> </span>                        </label>
                <button type="button" class="attribute-pager-btn action-next <?= $block->getMaxPageCount() === $block->getCurrentPageNumber() ? ' disabled"' :
                    '" data-url="' . $block->getNextUrl($block->getCurrentPageSize() , $block->getCurrentPageNumber() + 1); ?>">
                    <span><?= __('Next page'); ?></span>
                </button>
            </div>
        </div>
        <table class="data-table clearfix" cellspacing="0">
            <thead>
            <tr id="swatch-text-options-table">
                <th class="col-default"><span><?= $block->escapeHtml(__('Is Default')) ?></span></th>
                <?php foreach ($stores as $_store) : ?>
                    <th class="col-swatch col-swatch-min-width col-<%- data.id %><?= ($_store->getId() == \Magento\Store\Model\Store::DEFAULT_STORE_ID) ? ' _required' : '' ?>"
                        colspan="2">
                        <span><?= $block->escapeHtml($_store->getName()) ?></span>
                    </th>
                <?php endforeach; ?>
                <th class="col-swatch col-swatch-min-width col-<%- data.id %>"><span><?= $block->escapeHtml(__('Sort Order')) ?></span></th>
                <?php $colTotal = count($stores) * 2 + 3; ?>
                <th class="col-delete">&nbsp;</th>
            </tr>
            </thead>
            <tbody data-role="swatch-text-options-container" class="ignore-validate"></tbody>
            <tfoot>
            <tr>
                <th colspan="<?= (int)$colTotal ?>">
                    <input type="hidden" class="required-text-swatch-entry" name="text_swatch_validation"/>
                    <input type="hidden" class="required-text-swatch-unique" name="text_swatch_validation_unique"/>
                </th>
            </tr>
            <tr>
                <th colspan="<?= (int)$colTotal ?>" class="col-actions-add">
                    <?php if (!$block->getReadOnly() && !$block->canManageOptionDefaultOnly()) : ?>
                        <button id="add_new_swatch_text_option_button"
                                title="<?= $block->escapeHtml(__('Add Swatch')) ?>"
                                type="button" class="action- scalable add">
                            <span><?= $block->escapeHtml(__('Add Swatch')) ?></span>
                        </button>
                    <?php endif; ?>
                </th>
            </tr>
            </tfoot>
        </table>
        <input type="hidden" id="swatch-text-option-count-check" value="" />
    </div>
    <script id="swatch-text-row-template" type="text/x-magento-template">
        <tr>
            <td class="col-default">
                <input class="input-radio"
                       type="<%- data.intype %>"
                       name="defaulttext[]"
                       value="<%- data.id %>" <%- data.checked %><?= ($block->getReadOnly()) ? ' disabled="disabled"' : '' ?>/>
            </td>
            <?php foreach ($stores as $_store) : ?>
                <?php $storeId = (int)$_store->getId(); ?>
                <td class="col-swatch col-swatch-min-width col-<%- data.id %>">
                    <input class="input-text
                        swatch-text-field-<?= /* @noEscape */ $storeId ?>
                        <?= ($storeId == \Magento\Store\Model\Store::DEFAULT_STORE_ID) ? ' required-option required-unique' : '' ?>"
                           name="swatchtext[value][<%- data.id %>][<?= /* @noEscape */ $storeId ?>]"
                           type="text" value="<%- data.swatch<?= /* @noEscape */ $storeId ?> %>"
                           placeholder="<?= $block->escapeHtmlAttr(__("Swatch")) ?>"/>
                </td>
                <td class="col-swatch-min-width swatch-col-<%- data.id %>">
                    <input name="optiontext[value][<%- data.id %>][<?= /* @noEscape */ $storeId ?>]"
                           value="<%- data.store<?= /* @noEscape */ $storeId ?> %>"
                           class="input-text<?= ($storeId == \Magento\Store\Model\Store::DEFAULT_STORE_ID) ? ' required-option' : '' ?>"
                           type="text" <?= ($block->getReadOnly() || $block->canManageOptionDefaultOnly()) ? ' disabled="disabled"' : ''?>
                           placeholder="<?= $block->escapeHtmlAttr(__("Description")) ?>"/>
                </td>
            <?php endforeach; ?>
            <td class="col-swatch col-swatch-min-width swatch-col-<%- data.id %>">
                <?php if (!$block->getReadOnly() && !$block->canManageOptionDefaultOnly()) : ?>
                    <input data-role="order" type="text" name="optiontext[order][<%- data.id %>]" value="<%- data.sort_order %>" <?php if ($block->getReadOnly() || $block->canManageOptionDefaultOnly()) :?> disabled="disabled"<?php endif; ?>/>
                <?php endif; ?>
            </td>
            <td id="delete_button_swatch_container_<%- data.id %>" class="col-delete">
                <input type="hidden" class="delete-flag" name="optiontext[delete][<%- data.id %>]" value="" />
                <?php if (!$block->getReadOnly() && !$block->canManageOptionDefaultOnly()) : ?>
                    <button title="<?= $block->escapeHtmlAttr(__('Delete')) ?>" type="button"
                            class="action- scalable delete delete-option">
                        <span><?= $block->escapeHtml(__('Delete')) ?></span>
                    </button>
                <?php endif;?>
            </td>
        </tr>
    </script>
    <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Swatches/js/text": <?= /* @noEscape */ $block->getJsonConfig() ?> ,
                "Magento_Catalog/catalog/product/attribute/unique-validate": {
                    "element": "required-text-swatch-unique",
                    "message": "<?= $block->escapeJs($block->escapeHtml(__("The value of Admin must be unique."))) ?>"
                },
                "Nanobots_AttributeOptionPager/js/pager": {
                    "ajaxUrlValue": {}
                }
            }
        }
    </script>
</fieldset>
