<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 * Copyright © Q-Solutions Studio: eCommerce Nanobots. All rights reserved.
 * @author      Jakub Winkler <jwinkler@qsolutionsstudio.com>
 *
 * @category    Nanobots
 * @package     Nanobots_AttributeOptionPager
 */
// phpcs:disable PHPCompatibility.Miscellaneous.RemovedAlternativePHPTags.MaybeASPOpenTagFound
/** @var $block \Nanobots\AttributeOptionPager\Block\Adminhtml\Attribute\Edit\Options\Text */

$stores = $block->getStoresSortedBySortOrder();
?>
<fieldset class="admin__fieldset fieldset">
    <legend class="legend">
        <span><?= $block->escapeHtml(__('Manage Swatch (Values of Your Attribute)')) ?></span>
    </legend><br />
    <div class="admin__control-table-wrapper" id="swatch-visual-options-panel">
        <div class="admin__data-grid-pager-wrap attribute-pager">
            <label for="attributeGrid_page-limit"></label><select name="limit" id="attributeGrid_page-limit" class="admin__control-select attribute-pager-limit">
                <?php foreach ($block->getLimits() as $limit): ?>
                    <option value="<?= $limit;?>" <?= $block->getCurrentPageSize() === $limit ? 'selected="selected"' : '';?> data-url="<?= $block->getNextUrl($limit , $block->getCurrentPageNumber()); ?>"><?= $limit; ?></option>
                <?php endforeach; ?>
            </select>
            <label for="attributeGridattributeGrid_page-limit" class="admin__control-support-text"><?= __('per page'); ?></label>

            <div class="admin__data-grid-pager">
                <button type="button" class="attribute-pager-btn action-previous <?= $block->getCurrentPageNumber() === 1 ? 'disabled' :
                    '" data-url="' . $block->getNextUrl($block->getCurrentPageSize() , $block->getCurrentPageNumber() - 1); ?>">
                    <span><?= __('Previous page'); ?></span>
                </button>
                <input type="number" id="attributeGrid_page-current" min="1" max="<?= $block->getMaxPageCount() ?>" name="page" value="<?= $block->getCurrentPageNumber(); ?>"
                       data-url="<?= $block->getNextUrl($block->getCurrentPageSize() , 0) ?>" class="admin__control-text attribute-pager-current" data-ui-id="adminhtml-product-attribute-grid-current-page">
                <label class="admin__control-support-text" for="attributeGrid_page-current">
                    <?= __('of');?> <span> <?= $block->getMaxPageCount(); ?> </span>                        </label>
                <button type="button" class="attribute-pager-btn action-next <?= $block->getMaxPageCount() === $block->getCurrentPageNumber() ? ' disabled"' :
                    '" data-url="' . $block->getNextUrl($block->getCurrentPageSize() , $block->getCurrentPageNumber() + 1); ?>">
                    <span><?= __('Next page'); ?></span>
                </button>
            </div>
        </div>
        <table class="data-table clearfix" cellspacing="0">
            <thead>
            <tr id="swatch-visual-options-table">
                <th class="col-default"><span><?= $block->escapeHtml(__('Is Default')) ?></span></th>
                <th><span><?= $block->escapeHtml(__('Swatch')) ?></span></th>
                <?php foreach ($stores as $_store) : ?>
                    <th<?= ($_store->getId() == \Magento\Store\Model\Store::DEFAULT_STORE_ID) ? ' class="_required"' : '' ?>>
                        <span><?= $block->escapeHtml($_store->getName()) ?></span>
                    </th>
                <?php endforeach; ?>
                <th class="col-swatch col-swatch-min-width col-<%- data.id %>"><span><?= $block->escapeHtml(__('Sort Order')) ?></span></th>
                <?php $colTotal = count($stores) + 4; ?>
                <th class="col-delete">&nbsp;</th>
            </tr>
            </thead>
            <tbody data-role="swatch-visual-options-container" class="ignore-validate"></tbody>
            <tfoot>
            <tr>
                <th colspan="<?= (int)$colTotal ?>">
                    <input type="hidden" class="required-visual-swatch-entry" name="visual_swatch_validation"/>
                    <input type="hidden" class="required-visual-swatch-unique" name="visual_swatch_validation_unique"/>
                </th>
            </tr>
            <tr>
                <th colspan="<?= (int)$colTotal ?>" class="col-actions-add">
                    <?php if (!$block->getReadOnly() && !$block->canManageOptionDefaultOnly()) : ?>
                        <button id="add_new_swatch_visual_option_button"
                                title="<?= $block->escapeHtml(__('Add Swatch')) ?>"
                                type="button" class="action- scalable add">
                            <span><?= $block->escapeHtml(__('Add Swatch')) ?></span>
                        </button>
                    <?php endif; ?>
                </th>
            </tr>
            </tfoot>
        </table>
        <input type="hidden" id="swatch-visual-option-count-check" value="" />
    </div>
    <script id="swatch-visual-row-template" type="text/x-magento-template">
        <tr>

            <td class="col-default">
                <input class="input-radio" type="<%- data.intype %>" name="defaultvisual[]" value="<%- data.id %>" <%- data.checked %><?= ($block->getReadOnly()) ? ' disabled="disabled"' : '' ?>/>
            </td>
            <td class="swatches-visual-col col-default <%- data.empty_class %>">
                <?php //@todo add logic getting swatch value from db */ ?>
                <input id="swatch_visual_value_<%- data.id %>" type="hidden" name="swatchvisual[value][<%- data.id %>]" value="<%- data.defaultswatch0 %>" />
                <div class="swatch_window" id="swatch_window_option_<%- data.id %>" style="<%- data.swatch0 %>"></div>
                <div class="swatch_sub-menu_container" id="swatch_container_option_<%- data.id %>">
                    <div class="swatch_row position-relative">
                        <div class="swatch_row_name colorpicker_handler">
                            <p><?= $block->escapeHtml(__('Choose a color')) ?></p>
                        </div>
                    </div>
                    <div class="swatch_row">
                        <div class="swatch_row_name btn_choose_file_upload" id="swatch_choose_file_option_<%- data.id %>">
                            <p><?= $block->escapeHtml(__('Upload a file')) ?></p>
                        </div>
                    </div>
                    <div class="swatch_row">
                        <div class="swatch_row_name btn_remove_swatch">
                            <p><?= $block->escapeHtml(__('Clear')) ?></p>
                        </div>
                    </div>
                </div>
            </td>
            <?php foreach ($stores as $_store) : ?>
                <td class="swatch-col-<%- data.id %>">
                    <input name="optionvisual[value][<%- data.id %>][<?= (int)$_store->getId() ?>]"
                           value="<%- data.store<?= (int) $_store->getId() ?> %>"
                           class="input-text<?= ($_store->getId() == \Magento\Store\Model\Store::DEFAULT_STORE_ID) ? ' required-option required-unique' : '' ?>"
                           type="text" <?= ($block->getReadOnly() || $block->canManageOptionDefaultOnly()) ? ' disabled="disabled"' : '' ?>/>
                </td>
            <?php endforeach; ?>
            <td class="col-swatch col-swatch-min-width swatch-col-<%- data.id %>">
                <?php if (!$block->getReadOnly() && !$block->canManageOptionDefaultOnly()) : ?>
                    <input data-role="order" type="text" name="optionvisual[order][<%- data.id %>]" value="<%- data.sort_order %>" <?php if ($block->getReadOnly() || $block->canManageOptionDefaultOnly()) :?> disabled="disabled"<?php endif; ?>/>
                <?php endif; ?>
            </td>
            <td id="delete_button_swatch_container_<%- data.id %>" class="col-delete">
                <input type="hidden" class="delete-flag" name="optionvisual[delete][<%- data.id %>]" value="" />
                <?php if (!$block->getReadOnly() && !$block->canManageOptionDefaultOnly()) : ?>
                    <button title="<?= $block->escapeHtml(__('Delete')) ?>" type="button"
                            class="action- scalable delete delete-option">
                        <span><?= $block->escapeHtml(__('Delete')) ?></span>
                    </button>
                <?php endif;?>
            </td>
        </tr>
    </script>
    <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Swatches/js/visual": <?= /* @noEscape */ $block->getJsonConfig() ?> ,
                "Magento_Catalog/catalog/product/attribute/unique-validate": {
                    "element": "required-visual-swatch-unique",
                    "message": "<?= $block->escapeHtml(__("The value of Admin must be unique.")) ?>"
                },
                "Nanobots_AttributeOptionPager/js/pager": {
                    "ajaxUrlValue": {}
                }
            }
        }
    </script>
</fieldset>
